# Site settings
title: Morwicke
email: info@morwicke.com
url: https://morwicke.com/
description: "October 19th, 2019"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#cb5656'

# Footer settings
footer: Morwicke

# Build settings
markdown: kramdown
permalink: pretty
