# Site settings
title: Morwicke 2019
email: info@morwicke.com
url: https://morwicke.com/
description: "October 19th, 2019"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Morwicke

# Build settings
markdown: kramdown
permalink: pretty
